USE Gerir


CREATE TABLE Usuarios(
Id UNIQUEIDENTIFIER PRIMARY KEY,
Nome VARCHAR (150) NOT NULL,
Email VARCHAR (150) NOT NULL,
Senha VARCHAR (150) NOT NULL,
Tipo VARCHAR (100) NOT NULL
)
GO

CREATE TABLE Tarefas(
Id UNIQUEIDENTIFIER PRIMARY KEY,
Titulo VARCHAR (150) NOT NULL,
Descricao TEXT NOT NULL,
Categoria VARCHAR (150) NOT NULL,
DataEntrega DATETIME NOT NULL,
Status BIT,
Usuario_Id UNIQUEIDENTIFIER
FOREIGN KEY (Usuario_Id) REFERENCES Usuarios(Id) on DELETE CASCADE
)